awesome-academy/HN_Ruby_Intern_2023_Library_Management

app/assets/stylesheets/admin/base.css
app/controllers/admin/base_controller.rb
app/controllers/admin/sessions_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/sessions_controller.rb
app/helpers/admin/base_helper.rb
app/helpers/admin/users_helper.rb
app/models/account.rb
app/views/admin/base/_navbar_profile.html.erb
app/views/admin/base/_sidebar_profile.html.erb
app/views/admin/sessions/new.html.erb
app/views/admin/shared/_back_button.html.erb
app/views/admin/shared/_flash.html.erb
app/views/admin/shared/_profile.html.erb
app/views/admin/shared/_tab_content.html.erb
app/views/admin/users/_info_field.html.erb
app/views/admin/users/_status_button.html.erb
app/views/admin/users/_tab_profile.html.erb
app/views/admin/users/_user.html.erb
app/views/admin/users/change_status.turbo_stream.erb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
config/locales/admin/vi.yml
config/locales/en.yml
config/locales/vi.yml
config/settings.yml

- [ticket](https://edu-redmine.sun-asterisk.vn/issues/70789)
- Thêm chức năng active/inactive account
- Thêm chức năng xem chi tiết account
- Cập nhật lại SessionController để đảm bảo tài khoản bị inactive thì không đăng nhập được
- Sử dụng turbo-stream để active/inactive
- Sử dụng `send` để truy xuất thuộc tính model
- Chia nhỏ chức năng của UsersHelper Method
- Pass Rubocop
- Turbo-stream

Admin Account Detail

---

app/assets/stylesheets/admin/base.css
app/controllers/admin/books_controller.rb
app/controllers/admin/sessions_controller.rb
app/helpers/admin/books_helper.rb
app/helpers/admin/users_helper.rb
app/models/book.rb
app/views/admin/base/_navbar_profile.html.erb
app/views/admin/base/_sidebar.html.erb
app/views/admin/base/_sidebar_profile.html.erb
app/views/admin/books/_book.html.erb
app/views/admin/books/_tab_detail.html.erb
app/views/admin/books/index.html.erb
app/views/admin/books/new.html.erb
app/views/admin/books/show.html.erb
app/views/admin/shared/_form_button.html.erb
app/views/admin/shared/_info_field.html.erb
app/views/admin/users/_tab_profile.html.erb
app/views/admin/users/index.html.erb
app/views/admin/users/show.html.erb
config/locales/admin/vi.yml
db/migrate/20231201033737_add_column_is_active_for_book.rb
db/schema.rb

- [ticket](https://edu-redmine.sun-asterisk.vn/issues/70640)
- Thêm chức năng xem chi tiết và xóa Book
- Reformat I18n
- Xóa sử dụng Turbo Stream

Book Detail & Delete

---

app/assets/stylesheets/custom.scss
app/controllers/application_controller.rb
app/controllers/borrow_infos_controller.rb
app/controllers/borrow_items_controller.rb
app/controllers/carts_controller.rb
app/helpers/sessions_helper.rb
app/models/borrow_item.rb
app/models/cart.rb
app/views/books/show.html.erb
app/views/borrow_infos/index.html.erb
app/views/borrow_infos/new.html.erb
app/views/borrow_infos/show.html.erb
app/views/carts/_borrow_items.html.erb
app/views/carts/show.html.erb
app/views/layouts/_header.html.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/migrate/20231129155105_add_quantity_to_borrow_items.rb
db/migrate/20231129172451_change_borrow_infos_data_types.rb
db/migrate/20231129172840_add_default_values_to_borrow_infos.rb
db/migrate/20231204100256_create_carts.rb
db/migrate/20231204105622_add_cart_to_borrow_items.rb
db/migrate/20231204152240_change_column_null_borrow_items.rb
db/schema.rb
db/seeds.rb
spec/models/cart_spec.rb
spec/requests/borrow_infos_spec.rb
spec/requests/borrow_items_spec.rb
spec/requests/carts_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70621)
- Thực hiện chức năng giỏ lưu sách trước khi tạo yêu cầu mượn sách

User borrow cart

---

app/controllers/accounts_controller.rb
app/controllers/borrow_infos_controller.rb
app/controllers/borrow_items_controller.rb
app/controllers/sessions_controller.rb
app/helpers/sessions_helper.rb
app/models/borrow_info.rb
app/models/borrow_item.rb
app/views/accounts/edit.html.erb
app/views/accounts/new.html.erb
app/views/authors/show.html.erb
app/views/borrow_infos/new.html.erb
app/views/borrow_infos/show.html.erb
app/views/carts/_borrow_items.html.erb
app/views/layouts/_header.html.erb
app/views/shared/_book_card.html.erb
app/views/shared/_error_messages.html.erb
config/locales/en.yml
config/locales/vi.yml
db/migrate/20231207032934_remove_uniques_borrow_items.rb
db/schema.rb
db/seeds.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70620)
- Thực hiện tạo chức năng thông tin mượn sách của người dùng
- Xử lý thông tin mượn sách, thông tin của sách liên quan đến giỏ hàng và ttin mượn sách

User borrow information

---

app/controllers/admin/borrows_controller.rb
app/helpers/admin/base_helper.rb
app/helpers/admin/borrows_helper.rb
app/models/borrow_info.rb
app/views/admin/base/_sidebar.html.erb
app/views/admin/borrows/_borrow.html.erb
app/views/admin/borrows/index.html.erb
app/views/admin/borrows/show.html.erb
app/views/admin/home/index.html.erb
app/views/admin/shared/_index.html.erb
config/locales/admin/vi.yml
config/routes.rb
config/settings.yml
db/seeds.rb
spec/helpers/admin/borrows_helper_spec.rb
spec/requests/admin/borrows_spec.rb
spec/views/admin/borrows/index.html.erb_spec.rb
spec/views/admin/borrows/show.html.erb_spec.rb

- [ticket](https://edu-redmine.sun-asterisk.vn/issues/70628)
- Chức năng xem danh sách phiếu mượn
- Pending, Approved và History
- Sort/Search cho danh sách phiếu mượn

Borrow List

---

app/assets/stylesheets/admin/common.css
app/assets/stylesheets/admin/sessions.css
app/controllers/admin/base_controller.rb
app/controllers/admin/borrows_controller.rb
app/controllers/admin/passwords_controller.rb
app/controllers/admin/sessions_controller.rb
app/javascript/admin/toast.js
app/models/account.rb
app/models/notification.rb
app/views/admin/base/_navbar_profile.html.erb
app/views/admin/base/_sidebar_profile.html.erb
app/views/admin/layouts/application.html.erb
app/views/admin/layouts/base.html.erb
app/views/admin/layouts/sessions.html.erb
app/views/admin/passwords/edit.html.erb
app/views/admin/passwords/new.html.erb
app/views/admin/sessions/new.html.erb
config/locales/admin/en.yml
config/locales/admin/vi.yml
config/locales/devise.en.yml
config/locales/devise.vi.yml
config/routes.rb
db/seeds.rb

- [ticket](https://edu-redmine.sun-asterisk.vn/issues/70652)
- Đăng nhập, Đăng xuất, Quên mật khẩu cho Admin với Devise
- Đảm bảo tài khoản Inactive không thể đăng nhập thành công
- `devise`, `cancancan`

Devise for Admin

---

app/assets/stylesheets/actiontext.css
app/assets/stylesheets/application.scss
app/controllers/book_comments_controller.rb
app/controllers/books_controller.rb
app/javascript/application.js
app/models/book_comment.rb
app/views/active_storage/blobs/_blob.html.erb
app/views/book_comments/_comment.html.erb
app/views/book_comments/_form.html.erb
app/views/book_comments/_load_more_btn.html.erb
app/views/book_comments/create.turbo_stream.erb
app/views/book_comments/destroy.turbo_stream.erb
app/views/books/index.html.erb
app/views/books/show.html.erb
app/views/books/show.turbo_stream.erb
app/views/layouts/_footer.html.erb
app/views/layouts/action_text/contents/_content.html.erb
app/views/layouts/application.html.erb
config/importmap.rb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/migrate/20231221032924_remove_content_from_book_comments.rb
db/migrate/20231221033048_create_action_text_tables.action_text.rb
db/migrate/20231221043601_remove_unique_book_comments.rb
db/schema.rb
spec/requests/book_comments_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70623)
- Thực hiện chức năng comment của user
- Sử dụng rich text để nhập comment
- Tạo và xóa comment sử dụng turbo stream
- Load more button pagination cho comment

User book comment

---

app/assets/stylesheets/custom.scss
app/controllers/book_comments_controller.rb
app/controllers/books_controller.rb
app/controllers/borrow_items_controller.rb
app/controllers/notifications_controller.rb
app/helpers/notifications_helper.rb
app/models/account.rb
app/models/notification.rb
app/views/book_comments/_comment.html.erb
app/views/borrow_items/create.turbo_stream.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/notifications/_notification.html.erb
app/views/notifications/index.turbo_stream.erb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/seeds.rb
spec/requests/notifications_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70629)
- Tạo chức năng user notification  
- Sử dụng turbo_stream và batch update cho chức năng user notification

User notification

---

app/assets/stylesheets/custom.scss
app/controllers/book_comments_controller.rb
app/models/book.rb
app/models/book_comment.rb
app/views/book_comments/_comment.html.erb
app/views/book_comments/_form.html.erb
app/views/book_comments/create.turbo_stream.erb
app/views/book_comments/destroy.turbo_stream.erb
app/views/books/_progress_bar.html.erb
app/views/books/_ratings.html.erb
app/views/books/_star_progress.html.erb
app/views/books/show.html.erb
config/locales/en.yml
config/locales/vi.yml
db/migrate/20231228182205_drop_table_book_rates.rb
db/migrate/20231228183021_add_star_rate_to_book_comments.rb
db/schema.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70633)
- Tạo chức năng star ratings cho từng sách 
- Sử dụng ajax tạo và render view star rating

User book rating

---

app/assets/stylesheets/custom.scss
app/controllers/accounts_controller.rb
app/controllers/books_controller.rb
app/controllers/home_controller.rb
app/helpers/accounts_helper.rb
app/javascript/base.js
app/javascript/carousel.js
app/javascript/toastr_options.js
app/models/account.rb
app/models/book.rb
app/views/accounts/_author_list.html.erb
app/views/accounts/show.html.erb
app/views/authors/show.html.erb
app/views/home/_books_carousel.html.erb
app/views/home/index.html.erb
app/views/layouts/_header.html.erb
config/breadcrumbs.rb
config/locales/en.yml
config/locales/vi.yml
db/seeds.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70645)
- Tạo recommendation book cho user
- Sử dụng carousel xuất view cho user
- Metaprogramming

User recommendation

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/jobs/report_job.rb
app/mailers/report_mailer.rb
app/models/account.rb
app/models/application_record.rb
app/views/admin/base/_nav_item.html.erb
app/views/admin/base/_sidebar.html.erb
app/views/report_mailer/week_report.html.erb
app/views/report_mailer/week_report.text.erb
config/application.rb
config/application.yml.example
config/initializers/sidekiq.rb
config/locales/admin/en.yml
config/locales/admin/vi.yml
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
config/schedule.rb
spec/jobs/report_job_spec.rb
spec/mailers/previews/report_mailer_preview.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71556)
- Gửi báo cáo hàng tuần cho Admin
- Tạo Active Job cho Weekly Report
- Sử dụng `whenever` để tạo Cronjob cho hệ thống
- `redis`, `sidekiq`, **Active Job**
- `whenever`

Background Job

---

app/assets/stylesheets/custom.scss
app/controllers/borrow_infos_controller.rb
app/helpers/borrow_infos_helper.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71931)
- Chỉnh sửa, thêm giao diện khi thêm status renewing
- Fix lỗi không vào được borrow info

Borrow info update

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/concerns/cart_actions.rb
spec/factories/authors.rb
spec/rails_helper.rb
spec/requests/authors_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71913)
- Viết unit test cho authors_controller
- factory_bot_rails
- rails-controller-testing

[Rspec] authors_controller

---

app/controllers/accounts/confirmations_controller.rb
app/models/account.rb
app/views/accounts/confirmations/new.html.erb
app/views/accounts/mailer/confirmation_instructions.html.erb
app/views/accounts/mailer/reset_password_instructions.html.erb
app/views/accounts/passwords/edit.html.erb
app/views/accounts/passwords/new.html.erb
app/views/accounts/sessions/new.html.erb
app/views/accounts/shared/_links.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/en.yml
config/locales/vi.yml
config/routes.rb
db/migrate/20240104062633_add_confirmable_to_accounts.rb
db/migrate/20240104175107_change_default_values_of_accounts.rb
db/schema.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/70641)
- Thực hiện chức năng đăng ký, quên mật khẩu
- Sử dụng gem devise, module confirmable thực hiện
- Gặp lỗi trong việc thiết lập 1 model devise cho 2 loại người dùng 
- Lỗi toastr khi reload không hiện

User activation email and reset password

---

spec/factories/accounts.rb
spec/requests/registrations_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71954)
- Viết unit test cho registrations_controller

[Rspec] registrations_controller 

---

spec/models/book_author_spec.rb
spec/models/book_genre_spec.rb
spec/models/cart_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/72009)
- Thực hiện viết unit test cho model book_author, book_genre và cart

[Rspec] book_author, book_genre, cart model

---

config/environments/test.rb
db/schema.rb
db/seeds.rb
spec/factories/carts.rb
spec/requests/sessions_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71955)
- Viết unit test cho accounts/session_controller

[Rspec] accounts/session_controller

---

spec/requests/author_followers_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/display_flash.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71934)
- Viết unit test cho author_followers_controller

[Rspec] author_followers_controller

---

app/models/notification.rb
spec/factories/notification.rb
spec/models/notification_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/72010)
- Thực hiện viết unit test cho model notification

[Rspec] notification model

---

db/schema.rb
spec/factories/publishers.rb
spec/models/publisher_spec.rb
spec/models/user_info_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/72053)
- Viết unit test cho publisher và user_info model

[Rspec] publisher and user_info model

---

db/schema.rb
spec/factories/books.rb
spec/requests/books_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71936)
- Viết unit test cho books_controller

[Rspec] books_controller

---

spec/factories/books.rb
spec/models/user_info_spec.rb
spec/requests/home_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71940)
- Thực hiện viết unit test cho home_controller

[Rspec] home_controller

---

app/controllers/accounts_controller.rb
spec/requests/accounts_spec.rb
spec/requests/authors_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71914)
- Viết unit test cho accounts_controller

[Rspec] accounts_controller

---

spec/requests/carts_spec.rb
spec/support/shared_examples/redirect_to.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71939)
- Viết unit test cho carts_controller

[Rspec] carts_controller

---

app/controllers/book_comments_controller.rb
spec/factories/book_comments.rb
spec/requests/book_comments_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71935)
- Viết unit test cho book_comments_controller

[Rspec] book_comments_controller 

---

app/controllers/notifications_controller.rb
spec/requests/notifications_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71941)
- Viết unit test cho notifications_controller

[Rspec] notifications_controller 

---

spec/factories/borrow_infos.rb
spec/requests/borrow_infos_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71937)
- Viết unit test cho borrow_infos_controller

[Rspec] borrow_infos_controller

---

app/controllers/admin/publishers_controller.rb
spec/requests/admin/publishers_spec.rb
spec/support/admin_shared.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71951)
- Test cho Admin Publishers Controller

[Rspec] Admin Publishers Controller

---

spec/requests/admin/authors_spec.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71942)

[Rspec] Admin Authors Controller

---

spec/factories/borrow_items.rb
spec/requests/borrow_items_spec.rb

- [ticket redmine](https://edu-redmine.sun-asterisk.vn/issues/71938)
- Viết unit test cho borrow_items_controller

[Rspec] borrow_items_controller

---

spec/requests/admin/genres_spec.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71946)
- Test cho Admin Genres Controller

[Rspec] Admin Genres Controller

---

spec/requests/admin/home_spec.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71947)

[Rspec] Admin Home Controller

---

app/controllers/admin/notifications_controller.rb
spec/requests/admin/notifications_spec.rb
spec/support/admin_shared.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71949)

[Rspec] Admin Notifications Controller

---

app/helpers/admin/home_helper.rb
app/javascript/admin/toast.js
app/models/book.rb
app/models/borrow_info.rb
app/views/admin/borrows/_show.html.erb
app/views/admin/shared/_notify.html.erb
app/views/borrow_infos/index.html.erb
app/views/borrow_infos/show.html.erb
db/seeds.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71952)
Có một số lỗi khi xử lý xóa sách (is_active: false)
- Cần sử dụng thuộc tính này để kiểm tra điều kiện cần cho một số tác vụ

Fix some errors with Book is_active

---

Gemfile
Gemfile.lock
app/controllers/api/application_controller.rb
app/controllers/api/v1/admin/base_controller.rb
app/controllers/api/v1/sessions_controller.rb
app/models/account.rb
app/serializers/account_serializer.rb
app/serializers/application_serializer.rb
config/application.rb
config/application.yml.example
config/initializers/inflections.rb
config/locales/api/en.yml
config/locales/api/vi.yml
config/routes.rb
db/migrate/20240115085230_add_api_authentication_token_to_accounts.rb
db/schema.rb
lib/jwt_auth.rb
spec/requests/api/v1/sessions_spec.rb
spec/support/api_shared.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71950)
- Setup cho phần API
- Authentication cho API

[API] Setup & Authentication

---

app/assets/stylesheets/admin/base.css
app/controllers/admin/books_controller.rb
app/controllers/api/application_controller.rb
app/controllers/api/v1/admin/base_controller.rb
app/controllers/api/v1/admin/books_controller.rb
app/controllers/concerns/admin/books_concern.rb
app/serializers/application_serializer.rb
app/serializers/book_serializer.rb
app/serializers/object_preview_serializer.rb
config/locales/api/en.yml
config/routes.rb
spec/requests/admin/notifications_spec.rb
spec/requests/api/v1/admin/books_spec.rb
spec/requests/api/v1/sessions_spec.rb
spec/support/admin_shared.rb
spec/support/api_shared.rb

- [Ticket](https://edu-redmine.sun-asterisk.vn/issues/71943)
- API cho Admin Books Controller

[API] Admin Books Controller
